### PR TITLE
Remove now_casting Dataset Usage and Adjust GSP Endpoints (#323)

### PR DESCRIPTION
**Pull request by peterdudfield**
* removed nowcasting_dataset

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

# Pull Request

## Description

_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes #

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
@roshnaeem The tests are still failing, can you see them?

**Comment by roshnaeem** [comment]
@peterdudfield, I removed the relevant test from test_system.py. I am not sure why GitHub tests are failing, can you help me with them and let me know how can I fix them?

**Comment by peterdudfield** [comment]
Screenshot 2024-03-11 at 22 08 59

**Comment by roshnaeem** [comment]
@peterdudfield, I have removed this function `test_gsp_boundaries()`, which the screenshots shows error in.

**Comment by peterdudfield** [comment]
> @peterdudfield, I have removed this function `test_gsp_boundaries()`, which the screenshots shows error in.

ah sorry, could you make enough PR and we'll get rid of this

**Comment by roshnaeem** [comment]
@peterdudfield, another PR?

**Comment by peterdudfield** [comment]
> @peterdudfield, another PR?

sorry my mistake, looks like it is now working

**Pull request merged**
