### PR TITLE
Remove now_casting Dataset Usage and Adjust GSP Endpoints

### LINKED ISSUE #314: remove nowcast_dataset from this repo
Would be greta to move `nowcasting_Dataset` out of this module. 

Might need to copy some files from this repo into here.

### PR DESCRIPTION
**Pull request by roshnaeem**
# Pull Request

## Description

Removed the `nowcasting_dataset` from `requirements.txt` and also its usage from [system.py](https://github.com/openclimatefix/uk-pv-national-gsp-api/blob/main/src/system.py)

Fixes #314 

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Have you run pytest locally?

**Comment by roshnaeem** [comment]
@peterdudfield, I ran the tests locally, and nothing changes in the test results after the changes.

**Comment by peterdudfield** [comment]
I think there is a test that needs to be removed? Do you mind opening a new PR?

**Comment by roshnaeem** [comment]
@peterdudfield, i opened the new PR https://github.com/openclimatefix/uk-pv-national-gsp-api/pull/326 to main branch, i see that you merged the last PR to `external-pr` branch, and not main. Let me know if I need to close this PR and open a new one.

**Pull request merged**
